services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "composer install && npm install && apache2-foreground"
    links:
      - db
    volumes:
      - ./:/var/www
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mariadb:10.6.21
    environment:
      MARIADB_ROOT_PASSWORD: ${PROJECT_DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${PROJECT_DB_DATABASE}
      MARIADB_USER: ${PROJECT_DB_USER}
      MARIADB_PASSWORD: ${PROJECT_DB_PASSWORD}
    ports:
      - "3306:3306"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${PROJECT_DB_ROOT_PASSWORD}